### ISSUE TITLE
Apply button overflow on the right

### ISSUE THREAD

**Issue by aidenfry1** [TheAlphamerc/flutter_plugin_filter_list#1] opened 2020-07-30 14:26 UTC
Hey mate,

Thanks for this lib, made my life super easy as I'm just mocking up something which needs a filter.
I am getting some overflow reporting on the apply button.
"A RenderFlex overflowed by 234 pixels on the right."

I am on an Android Moto g6,
I can fix it for my case by setting the width, but I'm hesitant to use that to resolve it for a real multi platform / device experience.

Maybe id like to do something like setting the margin myself, or enabling the text to auto scale to the device I am on?

![image](https://user-images.githubusercontent.com/37015356/88934768-ecdc7200-d278-11ea-8045-ce01d791f01d.png)

Thanks again!

**Comment by aidenfry1** [comment] 2020-07-30 16:10
I saw some additional help messages, incase its useful.

"Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView."

Thanks 👍

**Comment by jaykishnk** [comment] 2020-09-03 11:20
i am also facing the same error with this library have you find any resolution for this??

**Comment by aidenfry1** [comment] 2020-09-11 21:04
Not from me, I was only using it for a quick demo and it was fine for that.
Best bet would be to fork and fix it in the source code, should be simple
enough but I didn't look in detail. Good luck.

**Comment by TheAlphamerc** [comment] 2021-03-30 08:45
Guys, the issue is fixed so closing this for now, if someone face similar issue feel free to reopen this issue.

**Closed by TheAlphamerc** 2021-03-30 08:45 UTC
